

[tool.poetry]
name = "vrp-mahm"
version = "0.1.0"
description = ""
authors = ["gustavojorge <gustavojorge080@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
# loguru = "^0.7.0"
# Adicione outras dependências aqui, se necessário


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
