

[tool.poetry]
name = "vrp-mahm"
version = "0.1.0"
description = ""
authors = ["gustavojorge <gustavojorge080@gmail.com>"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    # Adicione aqui apenas as dependências realmente usadas, por exemplo:
    # "loguru"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
